spring:
  datasource:
    url:  jdbc:h2:tcp://localhost/~/test
    username: bin
    password: h2db1234
    driver-class-name: org.h2.Driver
  h2.console:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
